wandb:
  name: "######"
  dir: "######/temp_file/wandb"
  entity: "######"
  tags: []
  project: "######"

# when on cluster, no wandb logs
cluster: False
replace_name: False

# 05
model_path: "######/temp_file/wandb/wandb/run-20230712_163549-1xh5hwjo/files/grid_baseline.pt"
pose_path: "######/temp_file/wandb/wandb/run-20230712_163549-1xh5hwjo/files/pose_baseline.pt"

# BEV size
bev_x_length: 100
bev_y_length: 100
bev_resolution: 0.1  # meters
bev_x_pixel: 1000
bev_y_pixel: 1000
cut_range: 7

# Training Parameters
waypoint_radius: 120  # meters
batch_size: 1
pos_enc: 5
lr: 
  vertices_rgb: 0.1
  vertices_label: 0.1
  vertices_z: 0.001
  rotations: 0.01
  translations: 0.01

lr_milestones: [1, 4]
lr_gamma: 0.1
seg_loss_weight: 1
normal_loss_weight: 0
laplacian_loss_weight: 10
rand_seed: 17
epochs: 1

# Performance Parameters
num_workers: 2


dataset: "NuscDataset"
version: "mini" 
base_dir: "######/Nuscenes"
image_dir: "######/nuScenes/"

clip_list:
- "scene-0655"

center_point:
  x: 0.0
  y: 0.0

# minimum distance between frame to sample the dataset
min_distance: 0.2

# resized image size
image_width: 800
image_height: 450

camera_names:
  - "CAM_FRONT"
  - "CAM_FRONT_LEFT"
  - "CAM_FRONT_RIGHT"
  - "CAM_BACK"
  - "CAM_BACK_LEFT"
  - "CAM_BACK_RIGHT"
